name: Clang-Format
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  Clang-Format:
    uses: steinwurf/clang-format-action/.github/workflows/action.yml@4.0.0

# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
