name: Cppcheck
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
    - master
jobs:
  docker_check:
    name: Cppcheck
    uses: steinwurf/cppcheck-action/.github/workflows/action.yml@2.0.0
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
