name: Cppcheck
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request:
jobs:
  docker_check:
    name: Cppcheck
    uses: steinwurf/cppcheck-action/.github/workflows/action.yml@2.0.0
