name: Linux Cmake
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
    - master
  pull_request:
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.extra_resolve_options }}
jobs:
  Linux-cmake:
    name: Linux Cmake
    uses: steinwurf/linux-cmake-action/.github/workflows/action.yml@4.0.0
    with:
      extra_resolve_options: $EXTRA_RESOLVE_OPTIONS
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
