env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.extra_resolve_options }}
jobs:
  Linux-cmake:
    name: Linux Cmake
    uses: steinwurf/linux-cmake-action/.github/workflows/action.yml@4.0.0
    with:
      extra_resolve_options: $EXTRA_RESOLVE_OPTIONS
name: Linux Cmake
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
