name: MacOS C++ make-specs
on:
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        required: false
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  MacOS-mkspecs:
    uses: steinwurf/macos-mkspecs-action/.github/workflows/action.yml@7.0.0
    with:
      extra_resolve_options: ${{ github.event.inputs.extra_resolve_options }}

# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
