jobs:
  MacOS-mkspecs:
    uses: steinwurf/macos-mkspecs-action/.github/workflows/action.yml@7.0.0
    with:
      extra_resolve_options: ${{ github.event.inputs.extra_resolve_options }}
name: MacOS C++ make-specs
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
