name: MacOS C++ make-specs
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request:
jobs:
  MacOS-mkspecs:
    uses: steinwurf/macos-mkspecs-action/.github/workflows/action.yml@7.0.0
    with:
      extra_resolve_options: ${{ github.event.inputs.extra_resolve_options }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
