jobs:
  valgrind:
    name: Valgrind
    uses: steinwurf/valgrind-action/.github/workflows/action.yml@5.0.0
    with:
      extra_resolve_options: ${{ github.event.inputs.extra_resolve_options }}
name: Valgrind
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
