name: Windows C++ make-specs
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request: null
jobs:
  Windows-mkspecs:
    uses: steinwurf/windows-mkspecs-action/.github/workflows/action.yml@6.0.0
    with:
      extra_resolve_options: ${{ github.event.inputs.extra_resolve_options }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
