name: Windows Cmake
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request: null
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.extra_resolve_options }}
jobs:
  Windows-cmake:
    name: Windows Cmake
    uses: steinwurf/windows-cmake-action/.github/workflows/action.yml@4.0.0
    with:
      extra_resolve_options: $EXTRA_RESOLVE_OPTIONS
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
